version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/zhaojkun/yinxiangblog

    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go run main.go
      - run: bash .circleci/scripts/deploy-ghpages.sh
      - persist_to_workspace:
          root: public
